[package]

name = "mysql"
version = "0.17.1"
authors = ["blackbeam"]
description = "Mysql client library implemented in rust"
license = "MIT"
documentation = "http://blackbeam.org/doc/mysql/index.html"
repository = "https://github.com/blackbeam/rust-mysql-simple"
keywords = ["database", "sql"]
exclude = ["tests/*", ".*", "Makefile"]

[lib]

name = "mysql"
path = "src/lib.rs"

[profile.dev]

opt-level = 0
debug = true

[profile.release]

opt-level = 3
debug = false

[profile.test]

opt-level = 0
debug = true

[profile.bench]

opt-level = 3
debug = false

[profile.doc]

opt-level = 0
debug = true

[features]
# default = ["ssl"]
# ssl = ["openssl"]
nightly = []

[dependencies]
lazy_static = "~0.1.0"
time = "~0.1.0"
bitflags = "~0.3.0"
byteorder = "~0.3.0"

[dependencies.regex]
version = "~0.1.0"
default-features = false

# [dependencies.openssl]
# version = "~0.6.0"
# optional = true

